### ISSUE TITLE
Windows Firefox Identifies File As WinRAR Zip Archive

### ISSUE THREAD

**Issue by pigeontoe** [egeriis/zipcelx#18]
Everything seems to be working well, however Windows Firefox indentifies the file as a WinRAR Zip Archive from: Blob. Meanwhile, Windows Chrome seems to treat it like any other excel file. Any idea what's causing this?

The file opens in excel no problem, the user just sees a window asking if they want to open it with winRAR Archiver, which is inconvenient. Unfortunately this is the browser and OS that our main client uses 100% of the time!

**Comment by yaseek** [comment]
It's need to add mimeType 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' to invocation of zip.generateAsync as:
```
return zip.generateAsync({
        type: 'blob',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    })
```

**Comment by egeriis** [comment]
Did you specify a filename with `.xlsx` ending? Feel free to open a PR w/a thoroughly tested solution 🙂

**Comment by egeriis** [comment]
Closed due to lack of activity
