### ISSUE TITLE
Cannot build in create-react-app

### ISSUE THREAD

**Issue by hermanfenderson** [egeriis/zipcelx#24]
I am having this issue: npm run build fails to minify.

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by hermanfenderson** [comment]
Just a quick update on this...
I transpiled with babel /lib/module.js and of course it built OK. 
So if only you could add a transpile to ES5 in the build process... it could work OK for all create-react-app users.

**Comment by egeriis** [comment]
Hey @hermanfenderson, we also have a ES5 build in `lib/bundle.js`. But I can see from the documentation that you linked, that it's probably not build as is should

> Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

I will look into this within the next few days.

**Comment by Nopzen** [comment]
Hey @hermanfenderson im not sure if these could be related but in #31 I'm talking about how i event cant import this in a create react app setup, can i ask if you have Ejected your create react app and is in full control over the webpack setup your self?

**Comment by SarantopoulosKon** [comment]
I'm getting the same problem with create-react-app (not ejected). Even though it's working perfectly, when i'm trying to build the project it fails, getting the same error as @hermanfenderson 

Thank you in advance!

**Comment by egeriis** [comment]
@SarantopoulosKon the lib/bundle.js file is gone, see #36 + #39 

Make sure to transpile zipcelx if necessary.

**Comment by egeriis** [comment]
Closing as this issue has no actionables.
