### ISSUE TITLE
Does it support styles?

### ISSUE THREAD

**Issue by vijaybritto** [egeriis/zipcelx#26]
Hi,
 I want to add styles to cells like width and background color. Is it possible now or is it in the plans?

**Comment by vijaybritto** [comment]
Saw the code and figured out that there is no support for styles. Are there plans to support this feature?

**Comment by egeriis** [comment]
We are trying to scope down the feature set, to provide a slim library. I don't know how much weight adding styles support would add, do you have some knowledge on the complexity of this feature?

If it weighs a lot, it may make sense to create plugin support in the core, then allow developers to pick and choose which features they wish to add through plugins.

**Comment by vijaybritto** [comment]
Isn't styles a basic feature? I'm not sure about the complexity here, but plugins would be a great way too


________________________________

**Comment by egeriis** [comment]
Not a basic feature by our definition: enable production of xlsx files client-side from json payload. 

This is our edge to more advanced client-side xlsx generators, we have a lightweight lib.

**Comment by vijaybritto** [comment]
Okay, I was able to achieve the styling using msexcel-builder. Thanks.
