### ISSUE TITLE
es6 import not working

### ISSUE THREAD

**Issue by Nopzen** [egeriis/zipcelx#31]
After developing #30 i stumbled across an issue, where I was not able to use the es6 `import` syntax, to import this module in a  non ejected`create-react-app` setup.

`create-react-app` before ejecting it has its own magical webpack setup, and upon digging abit I found a post on the webpack tracker that talked about multiple builds in npm module package file, and how webpack by default uses the `browser` key.

Upon inspecting our setup i saw the `lib/standalone.js` was the one stored on the browser key, when i tried to import this module the following error happens:

![skaermbillede 2018-03-23 kl 21 49 53](https://user-images.githubusercontent.com/2326591/37862862-5ff72566-2f54-11e8-9e7d-8af1d05e936f.png)

I tried to swap the `standalone.js` with the `bundle.js` and then everything works, I think there is a bug with the way `standalone.js` exports this module to the browsers.

I did find this post also on the webpack issue tracker, https://github.com/webpack/webpack/issues/1979 suggesting how you can order `mainFields` in your webpack resolver, but I haven't tested this or if this is remotly related to this case here.

**Comment by ichbinedgar** [comment]
I solved by using 
`import 'zipcelx'`
instead of 
`import zipcelx from 'zipcelx'`

**Comment by Nopzen** [comment]
@ichbinedgar Thanks, ill just try it out, but why is this happning ? i mean wont you need the from, to declare from which module you need to import from?

**Comment by ichbinedgar** [comment]
I'm not an expert, but what I understand is that is equivalent to 
`require('library_name');`

**Comment by egeriis** [comment]
`import 'zipcelx';` is perfectly valid. Just not the way it's supposed to work. I want to get this fixed asap, I'll use `create-react-app` to verify the build.

**Comment by guushamann** [comment]
i made a branch es6, I think this is how it should work, but i am not sure how to combine it with standalone
https://github.com/guushamann/zipcelx/tree/es6-version-only

changes are in 
https://github.com/guushamann/zipcelx/blob/es6-version-only/rollup.config.js
https://github.com/guushamann/zipcelx/blob/es6-version-only/src/zipcelx.js

**Comment by egeriis** [comment]
@guushamann Thank you for your contribution. There are a few things misunderstood from your changes:

#### Tree shaking

There's nothing to tree shake in zipcelx, there's only one export, so you don't get any benefits of doing a default vs named import. Neither should be the case for modules w/multiple exports, but that's irrelevant in this case.

#### Rollup config

We with to have all three builds still. The standalone build is to support the requests made by a few people: #19 (#13)
