### ISSUE TITLE
Uncaught (in promise) TypeError: (0 , _zipcelx2.default) is not a function

### ISSUE THREAD

**Issue by ichbinedgar** [egeriis/zipcelx#32]
Hi, I tried to use this library by using the example of the page "How to use"

But I received the following error when I tried to generate the file (a button that run the code):

"Uncaught (in promise) TypeError: (0 , _zipcelx2.default) is not a function"

EDIT: I solved by using **import 'zipcelx'** instead of **import zipcelx from 'zipcelx'**

**Comment by egeriis** [comment]
Thank you for noticing this. That is not the expected behavior, but I'm happy that you found a solution.
