### ISSUE TITLE
Manually refreshing a page with imported zipcelx crashes the app

### ISSUE THREAD

**Issue by Vojis** [egeriis/zipcelx#42]
Hi,

We have been using zipcelx for a few months for a React app (we **didn't** use Create React App to bootstrap the project) and initially everything worked just fine. However, we just started experiencing a few issues.

1 -- similar to already explained issues (e.g. [#31](https://github.com/egeriis/zipcelx/issues/31)), when trying to import the library to a new component, the app crashes.
2 -- some of the old components that already had zipcelx imported work on initial render. However, as soon as we manually refresh the page, the app crashes.

We have tried to remove the newest version of the library, and import either v1.3 or v1.2, but this did not solve the problem. Any idea what we could do? I have read answers to previous issues, but could not find any hint that is applicable to our problem.

Here's the screenshot of the error page.

<img width="1264" alt="screen shot 2018-06-15 at 13 51 02" src="https://user-images.githubusercontent.com/23516649/41454330-32b2e230-70a3-11e8-934c-fcad40d0a478.png">

**Comment by egeriis** [comment]
Sounds like this is unrelated to zipcelx? If using a previous version that worked for you before, it should still work unless you've changed something in your application.

The error you've screenshot though, seems to indicate that you're not transpiling zipcelx during build time. _This is new for zipcelx_, but a common practice for libs going forward to be written in ES6 and allows clients to decide which features their app needs transpiled.

**Comment by Vojis** [comment]
Thanks for the reply!

Unfortunately, we couldn't find a solution for this issue, so we had to write our own method to export to .csv file.

I'll close this issue now.
