### ISSUE TITLE
[BUG] Zipcelx make my Uglify crash

### ISSUE THREAD

**Issue by doliG** [egeriis/zipcelx#43]
Hey guys,

First and foremost, thanks you for the amazing work you did providing us this small and super usefull library. I was totally delighted when I found it (thanks to medium).

So I used it in our Angular application, and everythings ok, except when it came to minimize the code we're shipping.

I get the following error during production build : 
```
ERROR in ./dist/0.7da5d6ef.js from UglifyJs
Unexpected token: operator (>) [./dist/0.7da5d6ef.js:60268,32]
```

After investigation, it seems that Uglify doesn't support arrow function yet 😭 

I saw in #31 and #24 and #23 that there are others people wihch seems to have the same problem.

So far I've tried :
```js
// Prod compilation crash
import zipcelx from 'zipcelx';
// Prod compilation crash
import 'zipcelx';
// Prod compilation crash
import { zipcelx } from 'zipcelx';
// Prod compilation workgin but crahs in the console when trying to use it
import zipcelx from 'zipcelx/lib/standalone';
```

But no one is working. **So what is the correct way to use zipcelx without crashing Uglify ?**

Thanks :)

**Comment by benammann** [comment]
+1

`npm run build` on react

`Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/zipcelx/lib/module.js:16

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by doliG** [comment]
Hello @egeriis , and thanks for the quick reply.

I have to say I'm a real beginner when it comes to transpilation, babel, webpack and all this stuff.

I knew that I need to transpile it, but I don't really know how to transpile it correctly. Some explanations would be warmly welcomed.

**Comment by egeriis** [comment]
@doliG I assume from your reply that you're using webpack?

In that case you probably have some ignore rule for `node_module` in your webpack (babel-loader) or babel config. You would want to exclude zipcelx from the ignore rule. 

We have an open discussion on changing this a bit though, see #45. But you still want to make my suggested change.

**Comment by doliG** [comment]
Yes I am using webpack, and I'm using typescript too. So I'm not using babel and if possible, I'd like to avoid installing new dependencies only for transpiling one lib. Do you have any other solution ?

Thanks you, I had seen #45 before and think it's a great idea. In my opinion, all npm packages should be ready to use out of the box, without adding some builder configuration.

I wish you'll merge this PR 😋

**Comment by egeriis** [comment]
@doliG Yeah, unfortunately the PR is not finalized imo. 

> all npm packages should be ready to use out of the box

This is really arbitrary, because JavaScript support varies from browser to browser. The suit of browsers you wish to support differs from many others, this is why we have babel (and it's `env` preset). 

I haven't used TypeScript, but they're transpiling for you, right? E.g. if you use `import` statements, they'll likely get transformed in your build output.

**Comment by doliG** [comment]
Ok, so when do you think #45 will be finalized? I can help if needed.

Yes, this is arbitrary, and yes, there is a lot of various browsers and environments which run JavaScript. This is why I think it is important before shipping a package, to ensure that most of people could run it without trouble. And we have great tools for that, like babel.

Yes, Typescript use transpilation. The point here is not about transpiling or not. It is about transpiling **only** the project code, and not having to care about dependencies.

Imagine if we have to care in our builder config about tranpiling each package. It will become a nightmare. I'm sure you don't want that, and never do I.

So tell me if I can help in anything in making zipcelx usable for anyone. I'm not really good at these things, but if I can do something, I will try for sure.

**Comment by egeriis** [comment]
@doliG So unfortunately, as it goes with open source once in a while, that PR has stalled. 

I really appreciate your contributions. If you want to, I'd love to have that PR wrapped up. Not much needs to be done, simply what's outlined in my last comment.

**Comment by doliG** [comment]
Well, as I said in #48 , I have created a fork and changed the config.
It works on my project, but I'm not totally sure about what I've done 😋 

If you're interessed, you can review it [here](https://github.com/doliG/zipcelx-es5-cjs/commit/4131b7402170473496eaa642242528e72a37f149).

**Comment by egeriis** [comment]
@doliG Yeah, I took at look at it. It looks fine, except I would like to have a `module` build (the existing build) in addition to the CJS build (new `main`). Essentially what I outlined in #45 🙂

**Comment by doliG** [comment]
I'm afraid I don't understand what a module build is.
At first I was thinking that you means the "standalone" build. Now, I'm pretty sure I was wrong, but I still don't get what you mean by a "module build".

If you can point me some docs explaining what it is, it would be very helpful.
Thanks.

Cf https://github.com/egeriis/zipcelx/pull/45#issuecomment-416185149

**Comment by egeriis** [comment]
The module build is simply the existing one, but instead of removing it, point it to the path specified in package.json as `module` 🙂
