### ISSUE TITLE
Create excel table inside the sheet

### ISSUE THREAD

**Issue by pfigueiredo** [egeriis/zipcelx#46]
How to create an excel table in the sheet?
Can this be implemented?

**Comment by egeriis** [comment]
What do you mean with an excel table? Do you have an example?

**Comment by pfigueiredo** [comment]
Basically is a region of data, you can see an overview here:
https://support.office.com/en-us/article/overview-of-excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c

**Comment by egeriis** [comment]
Ah, I understand. No, that's out of scope for zipcelx unfortunately 🙂
