### ISSUE TITLE
NPM Module is not ES5 compatible 

### ISSUE THREAD

**Issue by davidryansoftware** [egeriis/zipcelx#48]
The built version of the code included in the NPM module is not babel transpiled. This causes errors when trying to build projects that depend on this module. 
To reproduce, 
1 - Create a new js app with create-react-app. 
2 - add zipcelx as a dependency.
3 - run the build.

outcome: you will get an error like the following 
"npm run build fails to minify"

**Comment by doliG** [comment]
More or less the same issue as #23 #24 #31 #43.

You should check PR #45.

**Comment by doliG** [comment]
If you want I just finish a realse which is ES5 tranpiled and shipped as CommonJS module.

It works on my project : https://www.npmjs.com/package/zipcelx-es5-cjs
