### ISSUE TITLE
Bundle up the module with Browserify

### ISSUE THREAD

**Issue by andreiho** [egeriis/zipcelx#7]
Maybe publish on Bower as well. We would find this useful for some of our older projects where we're still doing things the old fashioned way.

**Comment by Nopzen** [comment]
Hi @andreiho 

Thanks for your interest in `zipcelx`. 

I'm not super familiar with bower, but I will look at how to publish to bower tomorrow, I just did a bit of initial research if it's just creating a `bower.json` file and then link the dependencies as well that I have, I can totally do this "hopefully" over the weekend.

**Comment by pietersv** [comment]
This is a neat library, and works nicely in the browser.  Once browserify is installed, i was able to run the following command to create a bundle.  

```bash
browserify lib/zipcelx.js --standalone zipcelx > zipcelx.js
```
This could be added to the `package.json` as a script, e.g.
```json
"bundle": "browserify lib/zipcelx.js --standalone zipcelx > zipcelx.js"
```

With the HTML you can call the global variable `zipcelx` created by the `--standalone` argument.  Note that the zipcelx constructor is exported as `module.defaults` in the source code (`src/zipcelx.js:18`) so it's called here as `zipcelx.default(config)`

```html
  <script src="zipcelx.js" type="text/javascript"></script>
  <script type="text/javascript">
    zipcelx.default(config)
</script>
</body>
</html>
```

I currently get 525kb bundled, or 248MB minified with uglifyjs.

**Comment by egeriis** [comment]
Bower support is not really interesting anymore. NPM has taken over and works fine.

**Comment by andreiho** [comment]
@egeriis It isn't about the package manager, but rather about distributing the code so everyone can use it from the get-go, without any prerequisites.

Exporting it as a module will work if you're using a bundler like Browserify or Webpack, but won't work if you have a regular website. Here's how you'd do it: https://nolanlawson.com/2017/01/09/how-to-write-a-javascript-package-for-both-node-and-the-browser/

**Comment by egeriis** [comment]
@andreiho I may be missing something. But zipcelx is built for the browser. What is your use case exactly?

**Comment by andreiho** [comment]
@egeriis You're exporting the library as an ES6 module, which isn't supported in most browsers. So one would have to use Browserify or Webpack to bundle it up. That's perfectly fine, if you're using a bundler. But if you have a regular, old-school app or website where you include your libraries manually using <script> tags, you'll need a script that exposes the library on the window.

**Comment by andreiho** [comment]
Will work for most people building modern apps:

```
import zipcelx from 'zipcelx';
zipcelx(config);
```

However people building on legacy code will need to be able to do this:

```
window.zipcelx(config);
```

**Comment by egeriis** [comment]
@andreiho Right. Good point. 

Do you mind creating a PR which makes it part of the build process? I.e. keeps existing `lib` folder but adds some kind of `release` folder or whatever makes sense.
